config/routes.rb
Rails.application.routes.draw do
  get 'containers', to: 'containers#index' 
  resources :candidates, only: [:index] do
    put :approve, on: :member
  end

  resources :platform_products, only: [:show] do
    get :approved_products, on: :collection
  end
  resources :platforms
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  root 'store#index', as: 'store_index' 
  resources :products do
    get :who_bought, on: :member
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :platform_product
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end
  def total_price
    line_items.sum { |item| item.total_price }
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product
  belongs_to :cart, optional: true
  def total_price
    product.price * quantity
  end
end

app/models/order.rb
require 'active_model/serializers/xml'
require 'pago'

class Order < ApplicationRecord
  include ActiveModel::Serializers::Xml
  has_many :line_items, dependent: :destroy
  enum pay_type: {
    "Check"          => 0,
    "Credit card"    => 1,
    "Purchase order" => 2
  }
  validates :name, :adress, :email, presence: true
  validates :pay_type, inclusion: pay_types.keys

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def charge!(pay_type_params)
    payment_details = {}
    payment_method = nil
  
    case pay_type_params[:pay_type]
    when "Check"
      payment_method = :check
      payment_details[:routing] = pay_type_params[:routing_number]
      payment_details[:account] = pay_type_params[:account_number]
    when "Credit card"
      payment_method = :credit_card
      month, year = pay_type_params[:expiration_date].split('/')
      payment_details[:cc_num] = pay_type_params[:credit_card_number]
      payment_details[:expiration_month] = month
      payment_details[:expiration_year] = year
    when "Purchase order"
      payment_method = :po
      payment_details[:po_num] = pay_type_params[:po_number]
    end
  
    payment_result = Pago.make_payment(
      order_id: id,
      payment_method: payment_method,
      payment_details: payment_details
    )
  
    if payment_result.succeeded?
      OrderMailer.received(self).deliver_later
    else
      raise payment_result.error
    end
  end
  
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_many :platform_products, dependent: :destroy
end

app/models/platform_product.rb
class PlatformProduct < ApplicationRecord
  belongs_to :product
  belongs_to :platform

  has_many :candidates, dependent: :destroy
  has_many :transitions, dependent: :destroy, class_name: 'PlatformProductMachine::Transition', autosave: false
  has_many :platform_product_prices, dependent: :destroy

  include Statesman::Adapters::ActiveRecordQueries[
    transition_class: PlatformProductMachine::Transition,
    initial_state: :initialized,
    transition_name: :transitions
  ]

  def state_machine
    @state_machine ||= PlatformProductMachine::StateMachine.new(
      self,
      transition_class: PlatformProductMachine::Transition,
      association_name: :transitions
    )
  end

  delegate :can_transition_to?,
           :current_state, :history, :last_transition, :last_transition_to,
           :transition_to!, :transition_to, :in_state?, to: :state_machine

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
  has_many :platform_products, dependent: :destroy
  before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, :description, :image_url, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :title, uniqueness: true
  validates :image_url, allow_blank:true, format: {
    with: %r{\.(gif|jpg|png)\z}i,
    message: "Must be a URL for GIF, JPG or PNG image."
  }

  private
  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  after_destroy :ensure_an_admin_remains

  class Error < StandardError

  end

  private

  def ensure_an_admin_remains
    if User.count.zero?
      raise Error.new "Can't delete last user"
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<div class="w-full">
  <h1 class="mx-auto text-lg font-bold text-4xl">Welcome</h1>

  <p>
    It's <%= Time.now %>.
    We have <%= pluralize(@total_orders, "order") %>.
  </p>
</div>

app/views/layouts/_cart.html.erb
<% if @cart and not @cart.line_items.empty? %>
    <div id="cart" class="bg-white rounded p-2">
        <%= render @cart %>
    </div>
<% else %>
      <div id="cart" ></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pragprog Books Online Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application.tailwind", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="bg-green-700">
      <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf' %>
      <h1><%= @page_title %></h1>
    </header>

    <section class="flex">
      <nav class="bg-green-900 p-6">
        <%= render partial: 'layouts/cart', locals: {cart: @cart} %>

        <ul class="text-gray-300 leading-8">
          <li><a href="/">Home</a></li>
          <li><a href="/questions">Questions</a></li>
          <li><a href="/news">News</a></li>
          <li><a href="/contact">Contact</a></li>
        </ul>

        <% if session[:user_id]%>
          <hr class="my-2">
          <ul class="text-gray-300 leading-8">
            <li><%= link_to 'Orders', orders_path %></li>
            <li><%= link_to 'Products', products_path %></li>
            <li><%= link_to 'Users', users_path %></li>
            <li><%= link_to 'Container', containers_path %></li>
            <li><%= link_to 'Books', approved_products_platform_products_path %></li>
            <li><%= button_to 'Logout', logout_path, method: :delete %></li>
          </ul>
        <% end %>

      </nav>

      <main class="container mx-auto mt-4 px-5 flex">
        <%= yield %>
      </main>
    </section>
  </body>
</html>